version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: cineTogether
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cinetogether_net

  backend:
    build:
      context: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:12345678@db:5432/cineTogether
    command: ["/wait-for-it.sh", "db:5432", "--", "flask", "run", "--host=0.0.0.0"]
    depends_on:
      - db
    networks:
      - cinetogether_net
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - cinetogether_net

volumes:
  pgdata:

networks:
  cinetogether_net:
